//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.11.0
//     from Assets/Settings/NinjaZenControls.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @NinjaZenControls: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @NinjaZenControls()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""NinjaZenControls"",
    ""maps"": [
        {
            ""name"": ""map"",
            ""id"": ""6ea12aef-dbe5-4793-882b-a37b123038c3"",
            ""actions"": [
                {
                    ""name"": ""UR"",
                    ""type"": ""Button"",
                    ""id"": ""361f9c88-86c6-4602-96ec-5f1f97a0f5cc"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""UL"",
                    ""type"": ""Button"",
                    ""id"": ""b7209b66-84b9-4bef-9fe4-7c6ead3613ce"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""DR"",
                    ""type"": ""Button"",
                    ""id"": ""df780005-fbec-4f75-af5d-e6448b1f2e69"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""DL"",
                    ""type"": ""Button"",
                    ""id"": ""a7a2ddc0-4be6-41d0-aec6-62d918642904"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Accept"",
                    ""type"": ""Button"",
                    ""id"": ""488b4a36-7f6f-4e58-97c7-e0dab7c21f37"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Other"",
                    ""type"": ""Button"",
                    ""id"": ""6cc68dd9-13dc-49aa-9042-d6c9f5e9f110"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""8a1f9d85-39d4-44ad-9b0e-d70745cc098b"",
                    ""path"": ""<Keyboard>/numpad9"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""UR"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""61407d63-de89-4fd7-864c-443c14654449"",
                    ""path"": ""<Keyboard>/#(W)"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""UR"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""202304d4-8c65-436b-a4ee-097cbeaf1361"",
                    ""path"": ""<Gamepad>/rightTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""UR"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4aae089b-6984-461b-a746-1778cd9ac9f9"",
                    ""path"": ""<Keyboard>/numpad7"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""UL"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c55f4246-034c-45cf-8c00-8a91ca7a8b7e"",
                    ""path"": ""<Keyboard>/#(Q)"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""UL"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""aeadcbfe-7a70-45e0-94c5-81f0792e13c5"",
                    ""path"": ""<Gamepad>/leftTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""UL"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""804ff239-a840-4a08-a061-5e4166d59441"",
                    ""path"": ""<Keyboard>/numpad3"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""DR"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a77d7848-5f7d-4063-a899-cda93173761f"",
                    ""path"": ""<Keyboard>/#(S)"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""DR"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b5fda9ec-df81-40cc-b65a-f31a157ebb91"",
                    ""path"": ""<Gamepad>/rightShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""DR"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5a1bc077-961a-4328-a9e6-ad37b0f91141"",
                    ""path"": ""<Keyboard>/numpad1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""DL"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9e63a3d1-d8b3-4751-9e47-aea667427422"",
                    ""path"": ""<Keyboard>/#(A)"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""DL"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8aad9d4f-66e6-4d54-a2cc-768bdfc45eed"",
                    ""path"": ""<Gamepad>/leftShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""DL"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f2627bd7-fda7-4a2a-8df7-65d5ed802811"",
                    ""path"": ""<Keyboard>/enter"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Keyboard"",
                    ""action"": ""Accept"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2418eb1d-08be-4284-b584-8aa924752d03"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Gamepad"",
                    ""action"": ""Accept"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1634a7ae-dbe4-431c-a1ab-d5611ee1cef3"",
                    ""path"": ""<Keyboard>/backspace"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Other"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ca5033fc-2698-439e-abee-74d1e8ebbad0"",
                    ""path"": ""<Gamepad>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Other"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": [
        {
            ""name"": ""Keyboard"",
            ""bindingGroup"": ""Keyboard"",
            ""devices"": [
                {
                    ""devicePath"": ""<Keyboard>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        },
        {
            ""name"": ""Gamepad"",
            ""bindingGroup"": ""Gamepad"",
            ""devices"": [
                {
                    ""devicePath"": ""<Gamepad>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        }
    ]
}");
        // map
        m_map = asset.FindActionMap("map", throwIfNotFound: true);
        m_map_UR = m_map.FindAction("UR", throwIfNotFound: true);
        m_map_UL = m_map.FindAction("UL", throwIfNotFound: true);
        m_map_DR = m_map.FindAction("DR", throwIfNotFound: true);
        m_map_DL = m_map.FindAction("DL", throwIfNotFound: true);
        m_map_Accept = m_map.FindAction("Accept", throwIfNotFound: true);
        m_map_Other = m_map.FindAction("Other", throwIfNotFound: true);
    }

    ~@NinjaZenControls()
    {
        UnityEngine.Debug.Assert(!m_map.enabled, "This will cause a leak and performance issues, NinjaZenControls.map.Disable() has not been called.");
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // map
    private readonly InputActionMap m_map;
    private List<IMapActions> m_MapActionsCallbackInterfaces = new List<IMapActions>();
    private readonly InputAction m_map_UR;
    private readonly InputAction m_map_UL;
    private readonly InputAction m_map_DR;
    private readonly InputAction m_map_DL;
    private readonly InputAction m_map_Accept;
    private readonly InputAction m_map_Other;
    public struct MapActions
    {
        private @NinjaZenControls m_Wrapper;
        public MapActions(@NinjaZenControls wrapper) { m_Wrapper = wrapper; }
        public InputAction @UR => m_Wrapper.m_map_UR;
        public InputAction @UL => m_Wrapper.m_map_UL;
        public InputAction @DR => m_Wrapper.m_map_DR;
        public InputAction @DL => m_Wrapper.m_map_DL;
        public InputAction @Accept => m_Wrapper.m_map_Accept;
        public InputAction @Other => m_Wrapper.m_map_Other;
        public InputActionMap Get() { return m_Wrapper.m_map; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(MapActions set) { return set.Get(); }
        public void AddCallbacks(IMapActions instance)
        {
            if (instance == null || m_Wrapper.m_MapActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_MapActionsCallbackInterfaces.Add(instance);
            @UR.started += instance.OnUR;
            @UR.performed += instance.OnUR;
            @UR.canceled += instance.OnUR;
            @UL.started += instance.OnUL;
            @UL.performed += instance.OnUL;
            @UL.canceled += instance.OnUL;
            @DR.started += instance.OnDR;
            @DR.performed += instance.OnDR;
            @DR.canceled += instance.OnDR;
            @DL.started += instance.OnDL;
            @DL.performed += instance.OnDL;
            @DL.canceled += instance.OnDL;
            @Accept.started += instance.OnAccept;
            @Accept.performed += instance.OnAccept;
            @Accept.canceled += instance.OnAccept;
            @Other.started += instance.OnOther;
            @Other.performed += instance.OnOther;
            @Other.canceled += instance.OnOther;
        }

        private void UnregisterCallbacks(IMapActions instance)
        {
            @UR.started -= instance.OnUR;
            @UR.performed -= instance.OnUR;
            @UR.canceled -= instance.OnUR;
            @UL.started -= instance.OnUL;
            @UL.performed -= instance.OnUL;
            @UL.canceled -= instance.OnUL;
            @DR.started -= instance.OnDR;
            @DR.performed -= instance.OnDR;
            @DR.canceled -= instance.OnDR;
            @DL.started -= instance.OnDL;
            @DL.performed -= instance.OnDL;
            @DL.canceled -= instance.OnDL;
            @Accept.started -= instance.OnAccept;
            @Accept.performed -= instance.OnAccept;
            @Accept.canceled -= instance.OnAccept;
            @Other.started -= instance.OnOther;
            @Other.performed -= instance.OnOther;
            @Other.canceled -= instance.OnOther;
        }

        public void RemoveCallbacks(IMapActions instance)
        {
            if (m_Wrapper.m_MapActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IMapActions instance)
        {
            foreach (var item in m_Wrapper.m_MapActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_MapActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public MapActions @map => new MapActions(this);
    private int m_KeyboardSchemeIndex = -1;
    public InputControlScheme KeyboardScheme
    {
        get
        {
            if (m_KeyboardSchemeIndex == -1) m_KeyboardSchemeIndex = asset.FindControlSchemeIndex("Keyboard");
            return asset.controlSchemes[m_KeyboardSchemeIndex];
        }
    }
    private int m_GamepadSchemeIndex = -1;
    public InputControlScheme GamepadScheme
    {
        get
        {
            if (m_GamepadSchemeIndex == -1) m_GamepadSchemeIndex = asset.FindControlSchemeIndex("Gamepad");
            return asset.controlSchemes[m_GamepadSchemeIndex];
        }
    }
    public interface IMapActions
    {
        void OnUR(InputAction.CallbackContext context);
        void OnUL(InputAction.CallbackContext context);
        void OnDR(InputAction.CallbackContext context);
        void OnDL(InputAction.CallbackContext context);
        void OnAccept(InputAction.CallbackContext context);
        void OnOther(InputAction.CallbackContext context);
    }
}
