//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.10.0
//     from Assets/Settings/NinjaZenControls.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @NinjaZenControls: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @NinjaZenControls()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""NinjaZenControls"",
    ""maps"": [
        {
            ""name"": ""map"",
            ""id"": ""6ea12aef-dbe5-4793-882b-a37b123038c3"",
            ""actions"": [
                {
                    ""name"": ""UR"",
                    ""type"": ""Button"",
                    ""id"": ""361f9c88-86c6-4602-96ec-5f1f97a0f5cc"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""UL"",
                    ""type"": ""Button"",
                    ""id"": ""b7209b66-84b9-4bef-9fe4-7c6ead3613ce"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""DR"",
                    ""type"": ""Button"",
                    ""id"": ""df780005-fbec-4f75-af5d-e6448b1f2e69"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""DL"",
                    ""type"": ""Button"",
                    ""id"": ""a7a2ddc0-4be6-41d0-aec6-62d918642904"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""8a1f9d85-39d4-44ad-9b0e-d70745cc098b"",
                    ""path"": ""<Keyboard>/numpad9"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""UR"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4aae089b-6984-461b-a746-1778cd9ac9f9"",
                    ""path"": ""<Keyboard>/numpad7"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""UL"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""804ff239-a840-4a08-a061-5e4166d59441"",
                    ""path"": ""<Keyboard>/numpad3"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DR"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5a1bc077-961a-4328-a9e6-ad37b0f91141"",
                    ""path"": ""<Keyboard>/numpad1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DL"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // map
        m_map = asset.FindActionMap("map", throwIfNotFound: true);
        m_map_UR = m_map.FindAction("UR", throwIfNotFound: true);
        m_map_UL = m_map.FindAction("UL", throwIfNotFound: true);
        m_map_DR = m_map.FindAction("DR", throwIfNotFound: true);
        m_map_DL = m_map.FindAction("DL", throwIfNotFound: true);
    }

    ~@NinjaZenControls()
    {
        UnityEngine.Debug.Assert(!m_map.enabled, "This will cause a leak and performance issues, NinjaZenControls.map.Disable() has not been called.");
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // map
    private readonly InputActionMap m_map;
    private List<IMapActions> m_MapActionsCallbackInterfaces = new List<IMapActions>();
    private readonly InputAction m_map_UR;
    private readonly InputAction m_map_UL;
    private readonly InputAction m_map_DR;
    private readonly InputAction m_map_DL;
    public struct MapActions
    {
        private @NinjaZenControls m_Wrapper;
        public MapActions(@NinjaZenControls wrapper) { m_Wrapper = wrapper; }
        public InputAction @UR => m_Wrapper.m_map_UR;
        public InputAction @UL => m_Wrapper.m_map_UL;
        public InputAction @DR => m_Wrapper.m_map_DR;
        public InputAction @DL => m_Wrapper.m_map_DL;
        public InputActionMap Get() { return m_Wrapper.m_map; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(MapActions set) { return set.Get(); }
        public void AddCallbacks(IMapActions instance)
        {
            if (instance == null || m_Wrapper.m_MapActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_MapActionsCallbackInterfaces.Add(instance);
            @UR.started += instance.OnUR;
            @UR.performed += instance.OnUR;
            @UR.canceled += instance.OnUR;
            @UL.started += instance.OnUL;
            @UL.performed += instance.OnUL;
            @UL.canceled += instance.OnUL;
            @DR.started += instance.OnDR;
            @DR.performed += instance.OnDR;
            @DR.canceled += instance.OnDR;
            @DL.started += instance.OnDL;
            @DL.performed += instance.OnDL;
            @DL.canceled += instance.OnDL;
        }

        private void UnregisterCallbacks(IMapActions instance)
        {
            @UR.started -= instance.OnUR;
            @UR.performed -= instance.OnUR;
            @UR.canceled -= instance.OnUR;
            @UL.started -= instance.OnUL;
            @UL.performed -= instance.OnUL;
            @UL.canceled -= instance.OnUL;
            @DR.started -= instance.OnDR;
            @DR.performed -= instance.OnDR;
            @DR.canceled -= instance.OnDR;
            @DL.started -= instance.OnDL;
            @DL.performed -= instance.OnDL;
            @DL.canceled -= instance.OnDL;
        }

        public void RemoveCallbacks(IMapActions instance)
        {
            if (m_Wrapper.m_MapActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IMapActions instance)
        {
            foreach (var item in m_Wrapper.m_MapActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_MapActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public MapActions @map => new MapActions(this);
    public interface IMapActions
    {
        void OnUR(InputAction.CallbackContext context);
        void OnUL(InputAction.CallbackContext context);
        void OnDR(InputAction.CallbackContext context);
        void OnDL(InputAction.CallbackContext context);
    }
}
